
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.2/Modules/FindGit.cmake:111 (find_program)"
      - "C:/Program Files/CMake/share/cmake-4.2/Modules/FetchContent.cmake:1884 (find_package)"
      - "C:/Program Files/CMake/share/cmake-4.2/Modules/FetchContent.cmake:1619 (__FetchContent_populateSubbuild)"
      - "C:/Program Files/CMake/share/cmake-4.2/Modules/FetchContent.cmake:2007 (__FetchContent_doPopulation)"
      - "C:/Program Files/CMake/share/cmake-4.2/Modules/FetchContent.cmake:1988:EVAL:1 (__FetchContent_Populate)"
      - "C:/Program Files/CMake/share/cmake-4.2/Modules/FetchContent.cmake:1988 (cmake_language)"
      - "pico_sdk_import.cmake:75 (FetchContent_Populate)"
      - "CMakeLists.txt:12 (include)"
    mode: "program"
    variable: "GIT_EXECUTABLE"
    description: "Git command line client"
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "git.cmd"
      - "git"
    candidate_directories:
      - "C:/Windows/System32/"
      - "C:/Windows/"
      - "C:/Windows/System32/wbem/"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/"
      - "C:/Windows/System32/OpenSSH/"
      - "C:/Users/ulma5/AppData/Local/Programs/MiKTeX/miktex/bin/x64/"
      - "C:/Program Files/Git/cmd/"
      - "C:/Program Files/MATLAB/R2023b/runtime/win64/"
      - "C:/Program Files/MATLAB/R2023b/bin/"
      - "C:/Program Files (x86)/GnuWin32/bin/"
      - "C:/Program Files/CMake/bin/"
      - "C:/Program Files (x86)/GNU Arm Embedded Toolchain/10 2021.10/bin/"
      - "C:/Program Files/picotool/"
      - "C:/Repositories/pico/pico-sdk/"
      - "C:/Users/ulma5/AppData/Local/Programs/Python/Python312/Scripts/"
      - "C:/Users/ulma5/AppData/Local/Programs/Python/Python312/"
      - "C:/Users/ulma5/AppData/Local/Microsoft/WindowsApps/"
      - "C:/Users/ulma5/AppData/Local/Programs/Microsoft VS Code/bin/"
      - "C:/Program Files/JetBrains/PyCharm Community Edition 2024.2.0.1/bin/"
      - "C:/Users/ulma5/AppData/Local/Atlassian/SourceTree/git_local/bin/"
    searched_directories:
      - "C:/Windows/System32/git.cmd.com"
      - "C:/Windows/System32/git.cmd.exe"
      - "C:/Windows/System32/git.cmd"
      - "C:/Windows/git.cmd.com"
      - "C:/Windows/git.cmd.exe"
      - "C:/Windows/git.cmd"
      - "C:/Windows/System32/wbem/git.cmd.com"
      - "C:/Windows/System32/wbem/git.cmd.exe"
      - "C:/Windows/System32/wbem/git.cmd"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/git.cmd.com"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/git.cmd.exe"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/git.cmd"
      - "C:/Windows/System32/OpenSSH/git.cmd.com"
      - "C:/Windows/System32/OpenSSH/git.cmd.exe"
      - "C:/Windows/System32/OpenSSH/git.cmd"
      - "C:/Users/ulma5/AppData/Local/Programs/MiKTeX/miktex/bin/x64/git.cmd.com"
      - "C:/Users/ulma5/AppData/Local/Programs/MiKTeX/miktex/bin/x64/git.cmd.exe"
      - "C:/Users/ulma5/AppData/Local/Programs/MiKTeX/miktex/bin/x64/git.cmd"
      - "C:/Program Files/Git/cmd/git.cmd.com"
      - "C:/Program Files/Git/cmd/git.cmd.exe"
      - "C:/Program Files/Git/cmd/git.cmd"
      - "C:/Program Files/MATLAB/R2023b/runtime/win64/git.cmd.com"
      - "C:/Program Files/MATLAB/R2023b/runtime/win64/git.cmd.exe"
      - "C:/Program Files/MATLAB/R2023b/runtime/win64/git.cmd"
      - "C:/Program Files/MATLAB/R2023b/bin/git.cmd.com"
      - "C:/Program Files/MATLAB/R2023b/bin/git.cmd.exe"
      - "C:/Program Files/MATLAB/R2023b/bin/git.cmd"
      - "C:/Program Files (x86)/GnuWin32/bin/git.cmd.com"
      - "C:/Program Files (x86)/GnuWin32/bin/git.cmd.exe"
      - "C:/Program Files (x86)/GnuWin32/bin/git.cmd"
      - "C:/Program Files/CMake/bin/git.cmd.com"
      - "C:/Program Files/CMake/bin/git.cmd.exe"
      - "C:/Program Files/CMake/bin/git.cmd"
      - "C:/Program Files (x86)/GNU Arm Embedded Toolchain/10 2021.10/bin/git.cmd.com"
      - "C:/Program Files (x86)/GNU Arm Embedded Toolchain/10 2021.10/bin/git.cmd.exe"
      - "C:/Program Files (x86)/GNU Arm Embedded Toolchain/10 2021.10/bin/git.cmd"
      - "C:/Program Files/picotool/git.cmd.com"
      - "C:/Program Files/picotool/git.cmd.exe"
      - "C:/Program Files/picotool/git.cmd"
      - "C:/Repositories/pico/pico-sdk/git.cmd.com"
      - "C:/Repositories/pico/pico-sdk/git.cmd.exe"
      - "C:/Repositories/pico/pico-sdk/git.cmd"
      - "C:/Users/ulma5/AppData/Local/Programs/Python/Python312/Scripts/git.cmd.com"
      - "C:/Users/ulma5/AppData/Local/Programs/Python/Python312/Scripts/git.cmd.exe"
      - "C:/Users/ulma5/AppData/Local/Programs/Python/Python312/Scripts/git.cmd"
      - "C:/Users/ulma5/AppData/Local/Programs/Python/Python312/git.cmd.com"
      - "C:/Users/ulma5/AppData/Local/Programs/Python/Python312/git.cmd.exe"
      - "C:/Users/ulma5/AppData/Local/Programs/Python/Python312/git.cmd"
      - "C:/Users/ulma5/AppData/Local/Microsoft/WindowsApps/git.cmd.com"
      - "C:/Users/ulma5/AppData/Local/Microsoft/WindowsApps/git.cmd.exe"
      - "C:/Users/ulma5/AppData/Local/Microsoft/WindowsApps/git.cmd"
      - "C:/Users/ulma5/AppData/Local/Programs/Microsoft VS Code/bin/git.cmd.com"
      - "C:/Users/ulma5/AppData/Local/Programs/Microsoft VS Code/bin/git.cmd.exe"
      - "C:/Users/ulma5/AppData/Local/Programs/Microsoft VS Code/bin/git.cmd"
      - "C:/Program Files/JetBrains/PyCharm Community Edition 2024.2.0.1/bin/git.cmd.com"
      - "C:/Program Files/JetBrains/PyCharm Community Edition 2024.2.0.1/bin/git.cmd.exe"
      - "C:/Program Files/JetBrains/PyCharm Community Edition 2024.2.0.1/bin/git.cmd"
      - "C:/Users/ulma5/AppData/Local/Atlassian/SourceTree/git_local/bin/git.cmd.com"
      - "C:/Users/ulma5/AppData/Local/Atlassian/SourceTree/git_local/bin/git.cmd.exe"
      - "C:/Users/ulma5/AppData/Local/Atlassian/SourceTree/git_local/bin/git.cmd"
      - "C:/Windows/System32/git.com"
      - "C:/Windows/System32/git.exe"
      - "C:/Windows/System32/git"
      - "C:/Windows/git.com"
      - "C:/Windows/git.exe"
      - "C:/Windows/git"
      - "C:/Windows/System32/wbem/git.com"
      - "C:/Windows/System32/wbem/git.exe"
      - "C:/Windows/System32/wbem/git"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/git.com"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/git.exe"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/git"
      - "C:/Windows/System32/OpenSSH/git.com"
      - "C:/Windows/System32/OpenSSH/git.exe"
      - "C:/Windows/System32/OpenSSH/git"
      - "C:/Users/ulma5/AppData/Local/Programs/MiKTeX/miktex/bin/x64/git.com"
      - "C:/Users/ulma5/AppData/Local/Programs/MiKTeX/miktex/bin/x64/git.exe"
      - "C:/Users/ulma5/AppData/Local/Programs/MiKTeX/miktex/bin/x64/git"
      - "C:/Program Files/Git/cmd/git.com"
    found: "C:/Program Files/Git/cmd/git.exe"
    search_context:
      ENV{PATH}:
        - "C:\\WINDOWS\\system32"
        - "C:\\WINDOWS"
        - "C:\\WINDOWS\\System32\\Wbem"
        - "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\"
        - "C:\\WINDOWS\\System32\\OpenSSH\\"
        - "C:\\Users\\ulma5\\AppData\\Local\\Programs\\MiKTeX\\miktex\\bin\\x64"
        - "C:\\Program Files\\Git\\cmd"
        - "C:\\Program Files\\MATLAB\\R2023b\\runtime\\win64"
        - "C:\\Program Files\\MATLAB\\R2023b\\bin"
        - "C:\\Program Files (x86)\\GnuWin32\\bin\\"
        - "C:\\Program Files\\CMake\\bin\\"
        - "C:\\Program Files (x86)\\GNU Arm Embedded Toolchain\\10 2021.10\\bin\\"
        - "C:\\Program Files\\picotool\\"
        - "C:\\Repositories\\pico\\pico-sdk\\"
        - "C:\\Program Files (x86)\\GNU Arm Embedded Toolchain\\10 2021.10\\bin"
        - "C:\\Users\\ulma5\\AppData\\Local\\Programs\\Python\\Python312\\Scripts\\"
        - "C:\\Users\\ulma5\\AppData\\Local\\Programs\\Python\\Python312\\"
        - "C:\\Users\\ulma5\\AppData\\Local\\Microsoft\\WindowsApps"
        - "C:\\Users\\ulma5\\AppData\\Local\\Programs\\Microsoft VS Code\\bin"
        - "C:\\Program Files\\JetBrains\\PyCharm Community Edition 2024.2.0.1\\bin"
        - "C:\\Users\\ulma5\\AppData\\Local\\Programs\\MiKTeX\\miktex\\bin\\x64\\"
